### ISSUE TITLE
Connect NES Classic?

### ISSUE THREAD

**Issue by ghost** [elierodrigue/Hakchi_HelpingHand#5]
In the current build, I tried to use option "5 - Apply cache clearing fix", but I keep getting a pop up window saying "Nes classic need to be connected". I have my NESC connected to my PC, and have tried option 5 without any buttons pressed on my console, with just the power button on, and even holding the reset button down when pressing the power button (like you do when you sync games in Hakchi2). No matter what button combination I am using, I still get the same window.

I'm sure it's something pretty simple that I am overlooking. Please let me know what it may be.

**Comment by elierodrigue** [comment]
It needs to be connected and powered on normally. 
I just released v1.2 have a look there, i just changed a bit the way it connect. 
You need to make sure Hakchi is not currently running however. 
Try this : 
Close hakchi, close helping hand. 
Restart nes classic. Make sure its fully powered down. 
Restart it normally. 
Start helping hand.

**Comment by ghost** [comment]
Okay, compression works perfectly in the latest version. Thank you.

I'm still getting the "Nes classic need to be connected" window. Just to make sure I'm trying this the way you are instructing, here's what I'm doing:

With Hakchi2 closed, Hakchi Helping Hand closed, and NES Classic connected to my PC (with the power button off):

* Press the power button on the NESC [after a few seconds, PC gives off the "Device Connect" tone]
* Start up Hakchi Helping Hand
* Click on "Apply savegame clearing fix"
* "Nes classic need to be connected" window pops up

[Added...]

I can click on the "Safely Remove Hardware and Eject Media" in my PC's Taskbar while the NESC is connected and powered on, and "Eject CLV-S-NESY" is an option, so it appears my PC is recognizing the console is connected, but Hakchi Helping Hand is not.

**Comment by elierodrigue** [comment]
Which version of the custom kernel did you last used?
It needs to have at least 2.14.

**Comment by ghost** [comment]
Actually I uninstalled Hakchi2, reverted back to stock, and did a fresh install of Hakchi2 version 2.16c. Everything should be current.

[Update...]

Okay. I think I got it to work. I opened the Filebrowser. The screen came up blank. I checked the USB cord. This prompted the PC "Device Disconnect" tone, followed by a "Device Connect" tone. The Filebrowser then started to display the files. I closed the Filebrowser, and noticed the "progress bar" on the right of Helping Hand showed my NESC's storage space. I tried the "Apply savegame cleaning fix", and got the following in the status:

Downloading chmenu script
Building fixed files
Uploading fixed files
Done

Now the box next to "Save game cleaning fix applied" under NES Mini Info is checked. Not sure what the issue was - first reaction would be a loose USB cord connection, but I tried more than one USB cord, and made sure the cord was not loose. And the PC recognized the NESC was connected. Could it be from disconnecting and reconnecting the NESC while Helping Hand was running? Really I'm not sure why what I did worked, but I think it was applied correctly. Thanks!

**Comment by elierodrigue** [comment]
It should handle disconnect / reconnect without issues...
